name: cabo_customer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  skeletons: ^0.0.3
  flutter_screenutil: ^5.6.0
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  shared_preferences: ^2.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  get_it: ^7.2.0
  injectable: ^2.1.0
  flutter_dotenv: ^5.0.2
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.2.0
  retrofit_generator: ^7.0.1
  isar_generator: ^3.1.0+1
  injectable_generator: ^2.1.3

flutter_gen:
  output: lib/core/automatic_generator
  line_length: 80
  integrations:
    flutter_svg: true  

flutter:
  generate: true
  uses-material-design: true
  assets:
    # - assets/icons
    # - assets/images
    # - assets/audios
    - .env